import type { CustomerProfile } from '../types';

export const DEFAULT_CUSTOMERS: CustomerProfile[] = [
  {
    id: 'mrs_sharma',
    name: 'Mrs. Sharma',
    segment: 'regular',
    preferredWave: 'morning',
    cadence: 1,
    visitOffset: 0,
    visitPattern: 'Every morning before school drop-off',
    usualBasket: [
      { productId: 'milk', quantity: 2 },
      { productId: 'bread', quantity: 1 },
    ],
    substitutionTolerance: 20,
    priceSensitivity: 35,
    trust: 82,
    visitCount: 0,
    successfulVisits: 0,
    failedVisits: 0,
    khataBalance: 0,
    remindersSent: 0,
    orderHistory: [],
  },
  {
    id: 'patel_family',
    name: 'Patel Family',
    segment: 'family',
    preferredWave: 'morning',
    cadence: 2,
    visitOffset: 0,
    visitPattern: 'Alternate mornings, larger breakfast basket',
    usualBasket: [
      { productId: 'milk', quantity: 3 },
      { productId: 'bread', quantity: 2 },
      { productId: 'eggs', quantity: 6 },
      { productId: 'bananas', quantity: 1 },
    ],
    substitutionTolerance: 35,
    priceSensitivity: 45,
    trust: 76,
    visitCount: 0,
    successfulVisits: 0,
    failedVisits: 0,
    khataBalance: 0,
    remindersSent: 0,
    orderHistory: [],
  },
  {
    id: 'cafe_uncle',
    name: 'Cafe Uncle',
    segment: 'bulk',
    preferredWave: 'morning',
    cadence: 3,
    visitOffset: 1,
    visitPattern: 'Bulk top-up when his tea stall runs low',
    usualBasket: [
      { productId: 'milk', quantity: 8 },
      { productId: 'bread', quantity: 3 },
    ],
    substitutionTolerance: 15,
    priceSensitivity: 55,
    trust: 68,
    visitCount: 0,
    successfulVisits: 0,
    failedVisits: 0,
    khataBalance: 0,
    remindersSent: 0,
    orderHistory: [],
  },
  {
    id: 'school_group',
    name: 'Ravi School Group',
    segment: 'student',
    preferredWave: 'afternoon',
    cadence: 1,
    visitOffset: 0,
    visitPattern: 'After school snack stop',
    usualBasket: [
      { productId: 'chips', quantity: 3 },
      { productId: 'cold_drinks', quantity: 2 },
      { productId: 'maggi', quantity: 2 },
    ],
    substitutionTolerance: 70,
    priceSensitivity: 75,
    trust: 72,
    visitCount: 0,
    successfulVisits: 0,
    failedVisits: 0,
    khataBalance: 0,
    remindersSent: 0,
    orderHistory: [],
  },
  {
    id: 'office_pantry',
    name: 'Office Pantry',
    segment: 'office',
    preferredWave: 'afternoon',
    cadence: 2,
    visitOffset: 1,
    visitPattern: 'Every other afternoon for team supplies',
    usualBasket: [
      { productId: 'milk', quantity: 4 },
      { productId: 'bread', quantity: 2 },
      { productId: 'cold_drinks', quantity: 3 },
    ],
    substitutionTolerance: 25,
    priceSensitivity: 40,
    trust: 70,
    visitCount: 0,
    successfulVisits: 0,
    failedVisits: 0,
    khataBalance: 0,
    remindersSent: 0,
    orderHistory: [],
  },
  {
    id: 'hostel_boys',
    name: 'Hostel Boys',
    segment: 'snack',
    preferredWave: 'evening',
    cadence: 1,
    visitOffset: 0,
    visitPattern: 'Evening Maggi and eggs run',
    usualBasket: [
      { productId: 'maggi', quantity: 5 },
      { productId: 'eggs', quantity: 6 },
      { productId: 'cold_drinks', quantity: 2 },
    ],
    substitutionTolerance: 60,
    priceSensitivity: 55,
    trust: 74,
    visitCount: 0,
    successfulVisits: 0,
    failedVisits: 0,
    khataBalance: 0,
    remindersSent: 0,
    orderHistory: [],
  },
  {
    id: 'evening_walkers',
    name: 'Evening Walkers',
    segment: 'regular',
    preferredWave: 'evening',
    cadence: 2,
    visitOffset: 0,
    visitPattern: 'Light fruit and milk after the park',
    usualBasket: [
      { productId: 'bananas', quantity: 2 },
      { productId: 'milk', quantity: 1 },
    ],
    substitutionTolerance: 45,
    priceSensitivity: 35,
    trust: 80,
    visitCount: 0,
    successfulVisits: 0,
    failedVisits: 0,
    khataBalance: 0,
    remindersSent: 0,
    orderHistory: [],
  },
  {
    id: 'birthday_kids',
    name: 'Birthday Kids',
    segment: 'snack',
    preferredWave: 'evening',
    cadence: 5,
    visitOffset: 2,
    visitPattern: 'Occasional party snack burst',
    usualBasket: [
      { productId: 'chips', quantity: 6 },
      { productId: 'cold_drinks', quantity: 4 },
    ],
    substitutionTolerance: 50,
    priceSensitivity: 50,
    trust: 66,
    visitCount: 0,
    successfulVisits: 0,
    failedVisits: 0,
    khataBalance: 0,
    remindersSent: 0,
    orderHistory: [],
  },
];

export function cloneCustomers(customers: CustomerProfile[] = DEFAULT_CUSTOMERS): CustomerProfile[] {
  return customers.map((customer) => ({
    ...customer,
    usualBasket: customer.usualBasket.map((line) => ({ ...line })),
    orderHistory: customer.orderHistory.map((record) => ({
      ...record,
      requested: record.requested.map((line) => ({ ...line })),
      fulfilled: record.fulfilled.map((line) => ({ ...line })),
      missed: record.missed.map((line) => ({ ...line })),
    })),
  }));
}
