import type { NeighborhoodProfile } from '../types';

export const DEFAULT_NEIGHBORHOOD_PROFILE: NeighborhoodProfile = {
  id: 'nehru_colony_school_road',
  name: 'Nehru Colony School Road',
  shopLocation: {
    areaType: 'mixed residential school-road kirana catchment',
    roadType: 'colony connector road with school, bus stop, and evening commute movement',
    catchmentRadiusMeters: 700,
    footfallProfile: 'morning household essentials, afternoon students, evening commuters, weekend family top-ups',
  },
  nearbyPlaces: [
    {
      id: 'shyam_residency',
      name: 'Shyam Residency',
      type: 'residential_society',
      distanceMeters: 180,
      households: 220,
      population: 820,
      dominantSegments: ['family', 'regular'],
      peakWaves: ['morning', 'evening'],
      demandSignals: ['milk, bread, eggs, rice, oil, and quick family refills'],
    },
    {
      id: 'gokul_apartments',
      name: 'Gokul Apartments',
      type: 'residential_society',
      distanceMeters: 260,
      households: 150,
      population: 540,
      dominantSegments: ['family', 'walkin'],
      peakWaves: ['evening'],
      demandSignals: ['weekend grocery top-ups and offer-sensitive household purchases'],
    },
    {
      id: 'bright_public_school',
      name: 'Bright Public School',
      type: 'school',
      distanceMeters: 350,
      population: 900,
      dominantSegments: ['student', 'family', 'snack'],
      peakWaves: ['afternoon'],
      demandSignals: ['school-day snack bursts, Maggi, chips, cold drinks, and quick cash purchases'],
    },
    {
      id: 'colony_chowk_bus_stop',
      name: 'Colony Chowk Bus Stop',
      type: 'bus_stop',
      distanceMeters: 120,
      dailyPassersby: 2500,
      dominantSegments: ['office', 'walkin', 'snack'],
      peakWaves: ['morning', 'evening'],
      demandSignals: ['commuter impulse buys, cold drinks in heat, bread and eggs on return trips'],
    },
    {
      id: 'stationery_medical_lane',
      name: 'Stationery + Medical Lane',
      type: 'market_lane',
      distanceMeters: 90,
      dailyPassersby: 650,
      dominantSegments: ['walkin', 'student'],
      peakWaves: ['afternoon', 'evening'],
      demandSignals: ['walk-in add-ons from nearby errands and small basket purchases'],
    },
  ],
  demographics: [
    {
      segment: 'family',
      label: 'Residential Families',
      reachablePopulation: 1360,
      baseVisitRatePct: 4.2,
      peakWaves: ['morning', 'evening'],
      paymentStyle: 'cash_and_khata',
      basketStyle: 'essentials plus occasional monthly grocery top-ups',
      trustSensitivity: 'high',
      marketingSensitivity: 'medium',
      commonNeeds: ['milk', 'bread', 'eggs', 'bananas'],
      notes: ['trust drops when essentials are missed', 'khata reminders should be measured, not harsh'],
    },
    {
      segment: 'student',
      label: 'Students',
      reachablePopulation: 900,
      baseVisitRatePct: 2.8,
      peakWaves: ['afternoon'],
      paymentStyle: 'quick_cash',
      basketStyle: 'snacks and drinks after school',
      trustSensitivity: 'low',
      marketingSensitivity: 'high',
      commonNeeds: ['chips', 'maggi', 'cold_drinks'],
      notes: ['school days raise snack pressure', 'rain can reduce casual student walk-ins'],
    },
    {
      segment: 'office',
      label: 'Commuters',
      reachablePopulation: 2500,
      baseVisitRatePct: 1.1,
      peakWaves: ['morning', 'evening'],
      paymentStyle: 'quick_cash',
      basketStyle: 'quick return-home items and heat-driven drinks',
      trustSensitivity: 'medium',
      marketingSensitivity: 'low',
      commonNeeds: ['bread', 'eggs', 'cold_drinks', 'chips'],
      notes: ['evening commute creates impulse demand', 'hot days lift cold drink conversion'],
    },
    {
      segment: 'regular',
      label: 'Known Regulars',
      reachablePopulation: 80,
      baseVisitRatePct: 9.5,
      peakWaves: ['morning', 'evening'],
      paymentStyle: 'cash_and_khata',
      basketStyle: 'habit-led essentials and relationship purchases',
      trustSensitivity: 'high',
      marketingSensitivity: 'medium',
      commonNeeds: ['milk', 'bread', 'eggs', 'bananas'],
      notes: ['repeat misses hurt more than one-off walk-in misses', 'good service compounds loyalty'],
    },
    {
      segment: 'walkin',
      label: 'Road Walk-ins',
      reachablePopulation: 3150,
      baseVisitRatePct: 0.7,
      peakWaves: ['afternoon', 'evening'],
      paymentStyle: 'mostly_cash',
      basketStyle: 'small baskets from road traffic and nearby errands',
      trustSensitivity: 'medium',
      marketingSensitivity: 'medium',
      commonNeeds: ['chips', 'cold_drinks', 'bananas', 'maggi'],
      notes: ['rain lowers casual walk-ins', 'chalkboard and visible offers can pull this segment'],
    },
  ],
  commuteFlow: {
    roadName: 'Nehru Colony Connector Road',
    dailyPassersby: 2500,
    morningPeak: '8:00-10:00',
    eveningPeak: '17:30-20:30',
    impulseSegments: ['office', 'walkin', 'snack'],
    notes: ['evening traffic increases quick basket probability', 'weather affects walk-in conversion more than regulars'],
  },
  arenaFairnessNote: 'Fixed fictional profile used for every Arena run so model comparisons face the same demand context.',
  aiVisibleSignals: [
    'Two residential societies drive essentials and khata-sensitive regular demand.',
    'A 900-student school creates afternoon snack and cold drink pressure on school days.',
    'A 2,500-passersby connector road creates morning and evening commuter impulse demand.',
    'Rain reduces casual walk-ins; hot days lift cold drinks and quick snacks.',
    'Trust matters most for families and known regulars; marketing matters most for students and road walk-ins.',
  ],
};
