import type { ProductSpec, WeatherEffect } from '../types';

export const PRODUCTS: ProductSpec[] = [
  {
    id: 'milk',
    name: 'Milk',
    category: ['essential', 'perishable'],
    storage: 'fridge',
    baseDemand: 36,
    demandVariance: 8,
    shelfLife: 2,
    unit: 'L',
    margin: 8,
    costPrice: 42,
    sellPrice: 50,
    trustImpact: 'high',
    storageUnits: 1,
    orderIncrement: 5,
    perishabilityFactor: 1,
  },
  {
    id: 'bread',
    name: 'Bread',
    category: ['essential', 'perishable'],
    storage: 'shelf',
    baseDemand: 18,
    demandVariance: 4,
    shelfLife: 3,
    unit: 'packs',
    margin: 6,
    costPrice: 24,
    sellPrice: 30,
    trustImpact: 'high',
    storageUnits: 1,
    orderIncrement: 5,
    perishabilityFactor: 0.78,
  },
  {
    id: 'eggs',
    name: 'Eggs',
    category: ['essential', 'semi_perishable'],
    storage: 'shelf',
    baseDemand: 12,
    demandVariance: 3,
    shelfLife: 7,
    unit: 'eggs',
    margin: 3,
    costPrice: 7,
    sellPrice: 10,
    trustImpact: 'medium',
    storageUnits: 1,
    orderIncrement: 12,
    perishabilityFactor: 0.35,
  },
  {
    id: 'maggi',
    name: 'Maggi',
    category: ['essential', 'long_shelf'],
    storage: 'shelf',
    baseDemand: 20,
    demandVariance: 5,
    shelfLife: 60,
    unit: 'packets',
    margin: 4,
    costPrice: 11,
    sellPrice: 15,
    trustImpact: 'low',
    storageUnits: 1,
    orderIncrement: 10,
    perishabilityFactor: 0,
  },
  {
    id: 'chips',
    name: 'Chips',
    category: ['snack', 'long_shelf'],
    storage: 'shelf',
    baseDemand: 15,
    demandVariance: 5,
    shelfLife: 45,
    unit: 'packets',
    margin: 5,
    costPrice: 15,
    sellPrice: 20,
    trustImpact: 'low',
    storageUnits: 1,
    orderIncrement: 10,
    perishabilityFactor: 0,
  },
  {
    id: 'cold_drinks',
    name: 'Cold Drinks',
    category: ['event', 'long_shelf'],
    storage: 'fridge',
    baseDemand: 12,
    demandVariance: 4,
    shelfLife: 30,
    unit: 'bottles',
    margin: 10,
    costPrice: 20,
    sellPrice: 30,
    trustImpact: 'medium',
    storageUnits: 1,
    orderIncrement: 6,
    perishabilityFactor: 0.05,
  },
  {
    id: 'bananas',
    name: 'Bananas',
    category: ['perishable'],
    storage: 'counter',
    baseDemand: 5,
    demandVariance: 2,
    shelfLife: 2,
    unit: 'kg',
    margin: 15,
    costPrice: 35,
    sellPrice: 50,
    trustImpact: 'low',
    storageUnits: 1,
    orderIncrement: 1,
    perishabilityFactor: 0.95,
  },
];

export const WEATHER_EFFECTS: WeatherEffect[] = [
  { weather: 'normal', product: 'milk', multiplier: 1.0 },
  { weather: 'hot', product: 'milk', multiplier: 1.15 },
  { weather: 'very_hot', product: 'milk', multiplier: 1.30 },
  { weather: 'rainy', product: 'milk', multiplier: 0.95 },

  { weather: 'normal', product: 'cold_drinks', multiplier: 1.0 },
  { weather: 'hot', product: 'cold_drinks', multiplier: 1.60 },
  { weather: 'very_hot', product: 'cold_drinks', multiplier: 2.00 },
  { weather: 'rainy', product: 'cold_drinks', multiplier: 0.80 },

  { weather: 'normal', product: 'chips', multiplier: 1.0 },
  { weather: 'hot', product: 'chips', multiplier: 1.10 },
  { weather: 'very_hot', product: 'chips', multiplier: 1.20 },
  { weather: 'rainy', product: 'chips', multiplier: 0.90 },

  { weather: 'normal', product: 'bananas', multiplier: 1.0 },
  { weather: 'hot', product: 'bananas', multiplier: 1.15 },
  { weather: 'very_hot', product: 'bananas', multiplier: 1.30 },
  { weather: 'rainy', product: 'bananas', multiplier: 0.85 },
];

export const DEFAULT_CONFIG = {
  maxDays: 30,
  startingCash: 3000,
  startingTrust: 70,
  defaultCashReserve: 600,
  cashCrisisThreshold: 500,
  fridgeCapacity: 100,
  shelfCapacity: 200,
  shopSize: 300,
  tutorialDays: 3,
};

export const COLORS = {
  bgPrimary: '#F5F0EB',
  bgSecondary: '#EDE7E0',
  shopFloor: '#E8DDD0',
  shelfWood: '#92400E',
  panelBg: '#FFFFFF',
  panelBorder: '#E2E8F0',
  charcoal: '#1E293B',
  slate: '#475569',
  muted: '#94A3B8',
  success: '#10B981',
  profit: '#14B8A6',
  warning: '#F59E0B',
  danger: '#F43F5E',
  expiry: '#F97316',
  fridge: '#3B82F6',
  trust: '#8B5CF6',
  milk: '#DBEAFE',       // light blue-white
  bread: '#FDE68A',      // warm tan
  eggs: '#FEF3C7',       // cream
  maggi: '#FEF08A',      // yellow
  chips: '#FCA5A5',      // red
  coldDrinks: '#BFDBFE', // cool blue
  bananas: '#FCD34D',    // bright yellow
};

export const PRODUCT_COLORS: Record<string, string> = {
  milk: COLORS.milk,
  bread: COLORS.bread,
  eggs: COLORS.eggs,
  maggi: COLORS.maggi,
  chips: COLORS.chips,
  cold_drinks: COLORS.coldDrinks,
  bananas: COLORS.bananas,
};

export const DEMAND_MULTIPLIERS = {
  weekend: 1.15,
  festival: {
    milk: 1.25,
    bread: 1.35,
    eggs: 1.20,
    maggi: 1.15,
    chips: 1.65,
    cold_drinks: 1.80,
    bananas: 1.10,
  },
  school_reopening: {
    milk: 1.20,
    bread: 1.30,
    eggs: 1.15,
    maggi: 1.40,
    chips: 1.25,
    cold_drinks: 1.30,
    bananas: 1.05,
  },
};

export const TRUST_PENALTIES = {
  milk_stockout: 6,
  bread_stockout: 4,
  eggs_stockout: 2,
  maggi_stockout: 1,
  chips_stockout: 0,
  cold_drinks_stockout: 2,
  bananas_stockout: 0,
  repeated_stockout: 3,
};

export const TRUST_BONUSES = {
  essentials_available: 1,
  no_stockouts: 2,
  festival_prepared: 3,
};
